apiVersion: v1
kind: Pod
metadata:
  name: postinstall-hook
  annotations:
    "helm.sh/hook": "post-install"
spec:
  containers:
    - name: postinstall-hook
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo The Post Install hook pod is running"]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
