apiVersion: batch/v1
kind: Job
metadata:
  name: postinstalljob-hook
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec:
      containers:
        - name: postinstalljob-hook
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo post-install Job Pod is running"]
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
  backoffLimit: 3
  completions: 1
  parallelism: 1
