apiVersion: v1
kind: Pod
metadata:
  name: preinstall-hook
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  containers:
    - name: preinstall-hook
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "echo The Pre Install hook pod is running"]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
